spring:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/mybatis-interceptor?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8&amp&useSSL=false
    username: root
    password:
server:
  port: 8080
mybatis:
  type-aliases-package: yuwei35kd.mybatis.interceptor.bean
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    yuwei35kd:
      mybatis:
        interceptor:
          dao: debug
