spring:
  datasource:
    jdbc-url: jdbc:mysql://remotemysql.com:3306/FVXWVw0EqY
    username: FVXWVw0EqY
    password: izemFbfeyJ
server:
  port: 9090
mybatis:
  type-aliases-package: yuwei35kd.mybatis.interceptor.bean
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    yuwei35kd:
      mybatis:
        interceptor:
          dao: debug
